### ISSUE TITLE
Comments on the whitepaper

### ISSUE THREAD

**Issue by quiquee** [openblockchain/obc-docs#121]
This is an excellent and very complete starting point. I celebrate the inclusion of a target architecture that helps structuring thinking and separate concerns so early in the specs. Let me share some thoughts that I came across while reading the documentation

In general the doc should be continously reviewed to make sure it refers only to terms that are described in the glossary.

1. The whitepaper refers to blocks, which are not defined in the glossary:

>  "Efficiently calculating a cryptographic hash of the entire dataset after each block."

2. In the glossary is says solutions providers are limited to those developing browser or mobile applications, why this limit? could it not refer to "those developing computer based solutions to access OBC"  for example?

> "Organizations that develop mobile and/or browser based applications for end (solution) users to access chain networks. Some application owners may also be network owners."

3. The whitepaper includes implementation details, (gRPC, Docker or RocksDB...) mixed up with requirements. I believe implementation details can be part of the documentation that would come together with the proposed implementation, otherwise the whitepaper will become a technical documentation for a implementation of a self describing functionality. This does not help make evolve the functionality independently from a particular implementation. Please consider a fork of the whitepaper in two documents, one with use cases, requirements and architecture, the second one with implementation details.

**Comment by joshhus** [comment]
@nickgaski So the reviewer expects the whitepaper to be independent of a specific implementation, which should be reserved for the use cases document. Makes sense - if we mention an implementation in the whitepaper it should be as an example only. ... Adding block to glossary makes sense also.
