### ISSUE TITLE
Setting up the development environment.

### ISSUE THREAD

**Issue by xcross-ibm** [openblockchain/obc-docs#124]
I get the following from the vagrant up step in  obc-docs/dev-setup/devenv.md

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: box_version
* The box 'obc/dev-env' could not be found.

**Comment by jyellick** [comment]
@xcross-ibm What version of vagrant are you running? You can find this by executing:

`vagrant version`

**Comment by xcross-ibm** [comment]
@jyellick That was it, thanks! I installed vagrant from the Ubuntu repo which is still at 1.4.3.
