### ISSUE TITLE
A spelling mistake in Canonical-Use-Cases_One-Trade-One-Contract.png

### ISSUE THREAD

**Issue by genggjh** [openblockchain/obc-docs#128]
The picture wrongly says **Opperations**, instead of **Operations**.

**Comment by genggjh** [comment]
Where can I get the original editable file of the picture? it should be easy fixed.

**Comment by nickgaski** [comment]
@seanbarclay @joshhus  - Sean can you fix this typo?  We can't edit the images

**Comment by genggjh** [comment]
Fixed in https://github.com/openblockchain/obc-docs/commit/cbd2de762dff18a25a7cbcac7452dcdc4f24a082
