### ISSUE TITLE
Document incorrectly directs user to start his first VP as VP1

### ISSUE THREAD

**Issue by RicHernandez2** [openblockchain/obc-docs#138]
Description:

Document gives instructions to start you first Validating Peer as VP1, according to Tuan, we should always start with VP0

Steps to repro:

1.  Install system and bring up your first VP
2.  You are instructed to enter commandline:  docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer
3.  Open the Concensus yaml for any given consensus method
4.  All Consensus yaml files begin enumerating VPs at 0

Results:

There is a disparity between what the devs are writing in the yaml files and what the documents instruct a user to do

Expected results:

The yaml file content and the docs should be consistent with each other.

Additional, from Tuan:

richernandez2 5:48 PM I was just looking at the Sieve yaml and it begins enumerating the VPs at VP0, as does obcpbft , but the docs start at VP1-VPn, is this a documentation error, a yaml file error or a special case for sieve and obcpbft?
tuand27613
5:50 PM just different folks writing different things and not being consistent  ...  we should always do vp0-n  . can you open an issue against the docs ?

**Comment by RicHernandez2** [comment]
Fixed this myself, change has been merged, and verified.

**Comment by joshhus** [comment]
Thanks Ric!
