### ISSUE TITLE
We should be using unix format for all the text files.

### ISSUE THREAD

**Issue by genggjh** [openblockchain/obc-docs#145]
Need .gitattributes file to define the newline style.

**Comment by joshhus** [comment]
Unclear if GitHub supports the UNIX format - TBA - the entire file seems to now being "diffed" in the GitHub editor, if it was touched by a UNIX editor. Perhaps that only occurs the first instance, but many are using Windows and Macs.

**Comment by genggjh** [comment]
code has been merged.
