### ISSUE TITLE
Certificate Revocation List

### ISSUE THREAD

**Issue by szerge** [openblockchain/obc-docs#151]
Great work, yet I was surprised to read that you planned to use Certificate Revocation List, while other technologies, fully in line with distributed ledger technologies like https://guardtime.com/blt-technology are available and offer  "Simplified revocation management : In BLT, signing key status is checked at the signature issuance, and then the signature is sealed using KSI. There’s no need to find and check a Certificate Revocation List (CRL) when verifying the signature in the future."

CRL are a potential weak point if they are not systematically enforced. Using something like BLT would remove that weak point.

Is it something that you might want to add to your roadmap?

**Comment by tuand27613** [comment]
@szerge , could you move this issue to openblockchain/obc-peer ? Thanks !

**Comment by szerge** [comment]
Done
