### ISSUE TITLE
Devnet-setup.md - Incorrect index on first validating peer commandline

### ISSUE THREAD

**Issue by RicHernandez2** [openblockchain/obc-docs#154]
Description:  Incorrect vp1 ID is given for the first validating peer

Results:
![vp10](https://cloud.githubusercontent.com/assets/17052305/13761175/6372abf4-ea0d-11e5-8224-8fbe8be2e2da.JPG)

Expected Results:
The first Validating peer should have an ID of vp0

**Comment by RicHernandez2** [comment]
Please update so I can refer an external user to this doc without giving them bad info.

**Comment by kchristidis** [comment]
@RicHernandez2: I noted in another issue that you had created (in the `obc-peer` repo IIRC) that the first VP having an ID of `vp0` is only needed when the consensus plugin is `obc-*`.

In the document that you point to, we already note the following:

> In openchain.yaml, make sure the peer.id is set sequentially as vpX where X is an integer that starts from 0 and goes to N-1. For example, with 4 validating peers, set the peer.id to vp0, vp1, vp2, vp3.

**Comment by RicHernandez2** [comment]
Indeed, this is just cleaning up some inconsistencies, as the directions to bring up the VPs don't have the VP names starting at zero, especially necessary given that most people are going to copy and paste that gargantuan command line.  :D  I made the changes myself and put in a pull request, just trying to keep all docs consistent.

**Comment by kchristidis** [comment]
I hear you -- doesn't hurt to keep it consistent indeed.

**Comment by RicHernandez2** [comment]
Thanks!
