### ISSUE TITLE
SIEVE consensus algorithm

### ISSUE THREAD

**Issue by naddison36** [openblockchain/obc-docs#160]
Any idea when IBM Research will publish the research paper on the new SIEVE consensus algorithm?
Can we see a high level description of the algorithm in the mean time?

Thanks
Nick

**Comment by kchristidis** [comment]
@vukolic any estimates on when the technical report can be circulated?

**Comment by vukolic** [comment]
Eo this week is a good estimate



   Kostas Christidis --- Re: [obc-docs] SIEVE consensus algorithm (#160) --- 
    From:"Kostas Christidis" <notifications@github.com>To:"openblockchain/obc-docs" <obc-docs@noreply.github.com>Cc:"Marko Vukolic" <mvu@zurich.ibm.com>Date:Wed, Mar 23, 2016 04:07Subject:Re: [obc-docs] SIEVE consensus algorithm (#160)
  
  @vukolic any estimates on when the technical report can be circulated?

**Comment by joshhus** [comment]
Per @binh on slack:  http://www.zurich.ibm.com/~cca/papers/sieve.pdf
