### ISSUE TITLE
TCertOwner_EncryptKey should be in subscript in AES_Encrypt TCertOwner_EncryptKey ()

### ISSUE THREAD

**Issue by clydedacruz** [openblockchain/obc-docs#167]
In the protocol spec,
TCertOwner_EncryptKey should be in subscript in AES_Encrypt TCertOwner_EncryptKey ()

eg:

AES_Encrypt<sub>TCertOwner_EncryptKey</sub>(TCertIndex || known padding/parity check vector)

**Comment by clydedacruz** [comment]
#168

**Comment by angrbrd** [comment]
Closed with this PR to Hyperledger repo: https://github.com/hyperledger/fabric/pull/970

Closing issue.
