### ISSUE TITLE
OBCCA setup - docs are inconsistent

### ISSUE THREAD

**Issue by RicHernandez2** [openblockchain/obc-docs#172]
https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/obcca-setup.md#build-and-run

and 

https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md#security-setup-optional

Are in disagreement about the name of the CA server, and one seems to be calling it incorrectly (needs a "./" before server name)

**Comment by tuand27613** [comment]
@RicHernandez2 ,  create the issue on hyperledger/fabric repo

**Comment by RicHernandez2** [comment]
just noticed that, done.  ;)
